apiVersion: v1
kind: Secret
metadata:
  name: backend-env
type: Opaque
data:
  MONGO_URL: bW9uZ29kYitzcnY6Ly9zbGltOnRsc1NpUGdPZzFlbFl3U0xAY2x1c3RlcjAucGdpZWVraS5tb25nb2RiLm5ldC9HT1QtYXBwP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw
