apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-backend
  template:
    metadata:
      labels:
        app: portfolio-backend
    spec:
      containers:
      - name: portfolio-backend
        image: slimjemaidocker/portfolio-backend
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: backend-env
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-backend-service
spec:
  selector:
    app: portfolio-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000  # Use an available port, like 31000
  type: NodePort
