apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-frontend
  template:
    metadata:
      labels:
        app: portfolio-frontend
    spec:
      containers:
      - name: portfolio-frontend
        image: slimjemaidocker/portfolio-frontend
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-frontend-service
spec:
  selector:
    app: portfolio-frontend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
